[package]
name = "open-ralph"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
color-eyre = "0.6.5"
eyre = "0.6.12"
tokio = { version = "1.49.0", features = ["full"] }

[[bin]]
name = "openralph"
path = "src/main.rs"
